version: 0.2

env:
  parameter-store:
    DOCKER_HUB_USERNAME: "docker_hub_username"
    DOCKER_HUB_PASSWORD: "docker_hub_password"
    # store with: aws ssm put-parameter --name "docker_hub_username" --value "<username value>" --type String
phases:
  install:
    commands:
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export ACCOUNT=$(echo $CODEBUILD_BUILD_ARN |cut -f5 -d:)
      - export PROJECT_NAME=$(echo $CODEBUILD_BUILD_ID | sed -e 's/.*pipeline-\(.*\)-artifact.*/\1/')
      - export IMAGE_REPO_NAME="${DOCKER_HUB_USERNAME}/$PROJECT_NAME"
      - echo '***** This is the current env:'
      - printenv
  pre_build:
    commands:
      - echo Logging in to Docker Hub...
      - docker login -u ${DOCKER_HUB_USERNAME} -p ${DOCKER_HUB_PASSWORD}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - echo $IMAGE_TAG > code_hash.txt
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      # - docker build -t myimage .
  post_build:
    commands:
      - printf '[{"name":"example-backend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $IMAGE_REPO_NAME:$IMAGE_TAG
      # - docker pull anchore/cli
      # - docker run -d -v $(pwd):/source-dir -v /var/run/docker.sock:/var/run/docker.sock --name anchore anchore/cli:latest
      # - docker exec anchore anchore feeds sync
      # - docker exec anchore anchore analyze --image myimage --dockerfile /source-dir/Dockerfile

artifacts:
  files:
    - '**/*'
