version: 0.2

phases:
  install:
    commands:
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export ACCOUNT=$(echo $CODEBUILD_BUILD_ARN |cut -f5 -d:)
      - echo '***** This is the current env:'
      - printenv
      - curl -sS -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
      - curl -sS -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/kubectl
      - chmod +x ./kubectl ./aws-iam-authenticator
      - export PATH=$PWD/:$PATH
      #- apt-get update && apt-get -y install jq python3-pip python3-dev && pip3 install --upgrade awscli
      - apt-get update && apt-get -y install jq python3-pip && pip3 install --upgrade awscli
  pre_build:
      commands:
        - TAG="$REPOSITORY_NAME.$REPOSITORY_BRANCH.$ENVIRONMENT_NAME.$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
        - sed -i 's@brentley/ecsdemo-nodejs:latest@'"$REPOSITORY_URI:$TAG"'@' kubernetes/deployment.yaml
        - $(aws ecr get-login --no-include-email)
        - export KUBECONFIG=$HOME/.kube/config

      #- echo '***** Download nodejs repo:'
      #- curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
      #- echo '***** install nodejs:'
      #- apt-get install -y nodejs build-essential
      #- echo '***** install our npms:'
      #- npm install
  build:
    commands:
      #- echo '***** run tests:'
      #- npm test -- > testresult.txt
      # - docker build -t myimage .
      - docker build --tag $REPOSITORY_URI:$TAG .

  post_build:
    commands:
      - printf '[{"name":"example-backend","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo $IMAGE_TAG > code_hash.txt
      - docker push $REPOSITORY_URI:$TAG
      - CREDENTIALS=$(aws sts assume-role --role-arn $EKS_KUBECTL_ROLE_ARN --role-session-name codebuild-kubectl --duration-seconds 900)
      - export AWS_ACCESS_KEY_ID="$(echo ${CREDENTIALS} | jq -r '.Credentials.AccessKeyId')"
      - export AWS_SECRET_ACCESS_KEY="$(echo ${CREDENTIALS} | jq -r '.Credentials.SecretAccessKey')"
      - export AWS_SESSION_TOKEN="$(echo ${CREDENTIALS} | jq -r '.Credentials.SessionToken')"
      - export AWS_EXPIRATION=$(echo ${CREDENTIALS} | jq -r '.Credentials.Expiration')
      - aws eks update-kubeconfig --name $EKS_CLUSTER_NAME
      - kubectl apply -f kubernetes/deployment.yaml
      - kubectl apply -f kubernetes/service.yaml
      - printf '[{"name":"ecsdemo-nodejs","imageUri":"%s"}]' $REPOSITORY_URI:$TAG > build.json
      # - docker pull anchore/cli
      # - docker run -d -v $(pwd):/source-dir -v /var/run/docker.sock:/var/run/docker.sock --name anchore anchore/cli:latest
      # - docker exec anchore anchore feeds sync
      # - docker exec anchore anchore analyze --image myimage --dockerfile /source-dir/Dockerfile

artifacts:
  files:
    - '**/*'
